"""Safe model-adapter boundary for AI Model Terrarium."""

from .base import AdapterError, AdapterResult, AdapterStatus, AgentAdapter, JSONScalar, JSONValue
from .mock import DeterministicMockAdapter, MockAdapter
from .subprocess import (
    CommandNotAllowed,
    CommandSpec,
    DangerousSandboxPolicy,
    EnvironmentPolicy,
    JSONFailureCode,
    JSONParseFailure,
    JSONParseResult,
    NetworkMode,
    RuntimeLimits,
    RuntimeSecurityError,
    SandboxBackend,
    SandboxPolicy,
    SandboxUnavailable,
    StrictJSONError,
    SubprocessAdapter,
    SubprocessAgentAdapter,
    build_bubblewrap_argv,
    parse_structured_json,
    sanitize_terminal_text,
    strict_json_loads,
)

__all__ = [
    "AdapterError",
    "AdapterResult",
    "AdapterStatus",
    "AgentAdapter",
    "CommandNotAllowed",
    "CommandSpec",
    "DangerousSandboxPolicy",
    "DeterministicMockAdapter",
    "EnvironmentPolicy",
    "JSONFailureCode",
    "JSONParseFailure",
    "JSONParseResult",
    "JSONScalar",
    "JSONValue",
    "MockAdapter",
    "NetworkMode",
    "RuntimeLimits",
    "RuntimeSecurityError",
    "SandboxBackend",
    "SandboxPolicy",
    "SandboxUnavailable",
    "StrictJSONError",
    "SubprocessAdapter",
    "SubprocessAgentAdapter",
    "build_bubblewrap_argv",
    "parse_structured_json",
    "sanitize_terminal_text",
    "strict_json_loads",
]
